# Generated by Django 5.1.6 on 2025-07-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboardentry",
            options={},
        ),
        migrations.RenameField(
            model_name="leaderboardentry",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="leaderboardentry",
            name="operation",
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["operation", "digits", "num_questions", "average_time"],
                name="app_leaderb_operati_9cf2d1_idx",
            ),
        ),
    ]
